// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/menu/:slug": {
    params: {
      "slug": string;
    };
  };
  "/checkout": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/menu" | "/menu/:slug" | "/checkout" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/menu";
  };
  "routes/menu.$slug.tsx": {
    id: "routes/menu.$slug";
    page: "/menu/:slug";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/menu": typeof import("./app/routes/menu.tsx");
  "routes/menu.$slug": typeof import("./app/routes/menu.$slug.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
};